name: simple-pos
version: '0.1'
summary: A simple POS system for businesses
description: |
  A simple receipt maker and sales tracker.

grade: stable
confinement: strict

parts:
  simple-pos:
    plugin: nodejs
    node-version: '18.13.0'
    source: .
    build-packages:
      - nodejs
      - npm
    override-build: |
      set -e
      npm install -g npm@latest
      npm install
      npm run build
    stage-packages:
      - libnss3
      - libnspr4
      - libx11-xcb1
      - libxkbfile1

apps:
  simple-pos:
    command: electron . --no-sandbox
    plugs:
      - network
      - network-bind
      - x11
      - wayland
      - home
